// <auto-generated />
using Authorization.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Authorization.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180507153827_AddedTokenHashedField")]
    partial class AddedTokenHashedField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Authorization.API.Model.Telephone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Number");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Telephone");
                });

            modelBuilder.Entity("Authorization.API.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastLoginOn");

                    b.Property<DateTime>("LastUpdatedOn");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Password");

                    b.Property<int>("TelephoneId");

                    b.Property<byte[]>("TokenHashed");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Authorization.API.Model.Telephone", b =>
                {
                    b.HasOne("Authorization.API.Model.User")
                        .WithMany("Telephones")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
